apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: kafka_data  # This is now the bucket name
    user: admin
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
    isDefault: true
    version: 1
    editable: true