services:
  kafka-broker:
    image: apache/kafka:3.8.0
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:9093'
      KAFKA_LISTENERS: 'CONTROLLER://kafka-broker:9093,PLAINTEXT://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'test-broker'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - kafka-net

  kafka-consumer:
    build:
      context: ./kafka-consumer/
    environment:
      KAFKA_BROKER_URL: kafka-broker:9092
    networks:
      - kafka-net
    depends_on:
      - kafka-broker
    restart: "no"
    command: ["sh", "-c", "echo 'Waiting for Kafka to start' && sleep 30 && echo 'Starting consumer' && python consumer.py"]

  mqtt-kafka-producer:
    build:
      context: ./mqtt-kafka-producer/
    environment:
      KAFKA_BROKER_URL: kafka-broker:9092
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_TOPICS: ${MQTT_TOPICS}
    networks:
      - kafka-net
    depends_on:
      - kafka-broker
    restart: unless-stopped
    command: ["sh", "-c", "echo 'Waiting for Kafka to start' && sleep 10 && echo 'Starting MQTT-Kafka producer' && python mqtt_kafka_producer.py"]

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: kafka_data
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - kafka-net

  grafana-consumer:
    build: ./grafana-consumer/
    depends_on:
      - kafka-broker
      - influxdb
    environment:
      KAFKA_BROKER_URL: kafka-broker:9092
      KAFKA_TOPIC: my-topic
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_DB: kafka_data
      INFLUXDB_USER: admin
      INFLUXDB_PASS: admin123
    networks:
      - kafka-net

volumes:
  influxdb-data:
  grafana-storage:



networks:
  kafka-net:
    driver: bridge